// Static subject: the same selected c15t source, with only its color import
// redirected to the NO_COLOR identity shim generated by prepare.ts.
import { showHelpMenu } from "./generated/static/show-help-menu.ts";
import { commands, context, flags, VERSION } from "./help-fixture.ts";

showHelpMenu(context, VERSION, commands, flags);
